name: Generate vimdoc

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: README to vimdoc
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: extractor.nvim
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs: Generate doc/extractor.nvim.txt"
